/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.56
 * Generated at: 2026-07-12 18:35:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.voice4people.model.User;
import com.voice4people.dao.ComplaintDAO;

public final class citizenDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.voice4people.model.User");
    _jspx_imports_classes.add("com.voice4people.dao.ComplaintDAO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

User user = (User)session.getAttribute("user");

if(user == null){
    response.sendRedirect("login.jsp");
    return;
}

ComplaintDAO dao = new ComplaintDAO();

int total = dao.getUserTotalComplaints(user.getId());
int pending = dao.getUserPendingComplaints(user.getId());
int progress = dao.getUserInProgressComplaints(user.getId());
int resolved = dao.getUserResolvedComplaints(user.getId());

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>Citizen Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/dashboard.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".table-box{\r\n");
      out.write("    margin-top:30px;\r\n");
      out.write("    background:white;\r\n");
      out.write("    padding:20px;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    box-shadow:0 0 10px lightgray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-box p{\r\n");
      out.write("    font-size:16px;\r\n");
      out.write("    margin:10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\r\n");
      out.write("<h2>Voice4People</h2>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("Welcome,\r\n");
      out.write("\r\n");
      out.write("<b>");
      out.print(user.getFullName());
      out.write("</b>\r\n");
      out.write("\r\n");
      out.write("|\r\n");
      out.write("\r\n");
      out.write("<a href=\"../LogoutServlet\" style=\"color:white;text-decoration:none;\">Logout</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("<h2>Citizen</h2>\r\n");
      out.write("\r\n");
      out.write("<a href=\"citizenDashboard.jsp\">ð  Dashboard</a>\r\n");
      out.write("\r\n");
      out.write("<a href=\"submitComplaint.jsp\">â Submit Complaint</a>\r\n");
      out.write("\r\n");
      out.write("<a href=\"../MyComplaintsServlet\">ð My Complaints</a>\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\">ð Track Complaint</a>\r\n");
      out.write("\r\n");
      out.write("<a href=\"../ProfileServlet\">ð¤ My Profile</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("<h2>Citizen Dashboard</h2>\r\n");
      out.write("\r\n");
      out.write("<div class=\"cards\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("<h3>Total Complaints</h3>\r\n");
      out.write("\r\n");
      out.write("<h1>");
      out.print(total);
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("<h3>Pending</h3>\r\n");
      out.write("\r\n");
      out.write("<h1>");
      out.print(pending);
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("<h3>In Progress</h3>\r\n");
      out.write("\r\n");
      out.write("<h1>");
      out.print(progress);
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("<h3>Resolved</h3>\r\n");
      out.write("\r\n");
      out.write("<h1>");
      out.print(resolved);
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"table-box\">\r\n");
      out.write("\r\n");
      out.write("<h3>Quick Actions</h3>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<p>â Submit a new complaint using the <b>Submit Complaint</b> option.</p>\r\n");
      out.write("\r\n");
      out.write("<p>ð View all your complaints in <b>My Complaints</b>.</p>\r\n");
      out.write("\r\n");
      out.write("<p>ð Track complaint status anytime.</p>\r\n");
      out.write("\r\n");
      out.write("<p>ð Dashboard statistics update automatically after every complaint submission or status update.</p>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
