/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.56
 * Generated at: 2026-07-15 12:19:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import com.voice4people.model.Complaint;

public final class trackComplaint_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.voice4people.model.Complaint");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

List<Complaint> complaints =
    (List<Complaint>) request.getAttribute("complaints");

Map<Integer, List<String>> statusHistory =
    (Map<Integer, List<String>>)
    request.getAttribute("statusHistory");

if (complaints == null) {
    response.sendRedirect("citizenDashboard.jsp");
    return;
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>Track Complaints</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    font-family: Arial;\r\n");
      out.write("    background: #f2f2f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("    width: 90%;\r\n");
      out.write("    margin: 40px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #0d6efd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("    background: white;\r\n");
      out.write("    margin: 25px auto;\r\n");
      out.write("    padding: 25px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    box-shadow: 0 0 10px lightgray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".status {\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".timeline {\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    border-left: 4px solid #0d6efd;\r\n");
      out.write("    padding-left: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".history-item {\r\n");
      out.write("    margin-bottom: 25px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".history-item::before {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: -37px;\r\n");
      out.write("    top: 2px;\r\n");
      out.write("    width: 18px;\r\n");
      out.write("    height: 18px;\r\n");
      out.write("    background: #0d6efd;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".history-status {\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #0d6efd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pending {\r\n");
      out.write("    color: #dc3545;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".progress {\r\n");
      out.write("    color: #fd7e14;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".resolved {\r\n");
      out.write("    color: #198754;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".no-history {\r\n");
      out.write("    color: gray;\r\n");
      out.write("    font-style: italic;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".back {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 220px;\r\n");
      out.write("    margin: 30px auto;\r\n");
      out.write("    padding: 12px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    background: #0d6efd;\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<h2>🔍 Track My Complaints</h2>\r\n");
      out.write("\r\n");


if (complaints.isEmpty()) {


      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("<h3>No complaints found.</h3>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");


} else {

for (Complaint c : complaints) {

List<String> history =
    statusHistory.get(c.getId());


      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"title\">\r\n");
      out.write("\r\n");
      out.write("Complaint #");
      out.print(c.getId());
      out.write(" -\r\n");
      out.print(c.getTitle());
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"timeline\">\r\n");
      out.write("\r\n");


if (history != null &&
    !history.isEmpty()) {

for (String status : history) {

String statusClass = "";

if ("Pending".equalsIgnoreCase(status)) {

statusClass = "pending";

} else if ("In Progress".equalsIgnoreCase(status)) {

statusClass = "progress";

} else if ("Resolved".equalsIgnoreCase(status)) {

statusClass = "resolved";

}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"history-item\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"history-status ");
      out.print(statusClass);
      out.write("\">\r\n");
      out.write("\r\n");
      out.print(status);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("Status updated successfully\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");


}

} else {


      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"no-history\">\r\n");
      out.write("\r\n");
      out.write("No status history available.\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");


}


      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");


}

}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href=\"citizenDashboard.jsp\" class=\"back\">\r\n");
      out.write("\r\n");
      out.write("⬅ Back to Dashboard\r\n");
      out.write("\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
