/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.56
 * Generated at: 2026-07-15 12:45:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.voice4people.model.Complaint;

public final class viewComplaints_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.voice4people.model.Complaint");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>All Complaints</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("    font-family:Arial;\r\n");
      out.write("    background:#f2f2f2;\r\n");
      out.write("    margin:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container{\r\n");
      out.write("    width:95%;\r\n");
      out.write("    margin:30px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2{\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    color:#0d6efd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-box{\r\n");
      out.write("    background:white;\r\n");
      out.write("    padding:20px;\r\n");
      out.write("    margin-bottom:20px;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    box-shadow:0 0 10px lightgray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-box input,\r\n");
      out.write(".search-box select{\r\n");
      out.write("    padding:8px;\r\n");
      out.write("    margin-right:10px;\r\n");
      out.write("    border:1px solid #ccc;\r\n");
      out.write("    border-radius:5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-box button{\r\n");
      out.write("    padding:8px 15px;\r\n");
      out.write("    background:#0d6efd;\r\n");
      out.write("    color:white;\r\n");
      out.write("    border:none;\r\n");
      out.write("    border-radius:5px;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-box button:hover{\r\n");
      out.write("    background:#084298;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reset-btn{\r\n");
      out.write("    background:#6c757d !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reset-btn:hover{\r\n");
      out.write("    background:#495057 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table{\r\n");
      out.write("    width:100%;\r\n");
      out.write("    border-collapse:collapse;\r\n");
      out.write("    background:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table th{\r\n");
      out.write("    background:#0d6efd;\r\n");
      out.write("    color:white;\r\n");
      out.write("    padding:12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table td{\r\n");
      out.write("    padding:10px;\r\n");
      out.write("    border:1px solid #ddd;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    vertical-align:middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:nth-child(even){\r\n");
      out.write("    background:#f8f8f8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".status-select,\r\n");
      out.write(".priority-select{\r\n");
      out.write("    padding:6px;\r\n");
      out.write("    margin-top:5px;\r\n");
      out.write("    width:140px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".update-btn{\r\n");
      out.write("    margin-top:10px;\r\n");
      out.write("    padding:6px 12px;\r\n");
      out.write("    background:#198754;\r\n");
      out.write("    color:white;\r\n");
      out.write("    border:none;\r\n");
      out.write("    border-radius:5px;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".update-btn:hover{\r\n");
      out.write("    background:#146c43;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".complaint-image{\r\n");
      out.write("    width:120px;\r\n");
      out.write("    height:90px;\r\n");
      out.write("    object-fit:cover;\r\n");
      out.write("    border-radius:6px;\r\n");
      out.write("    border:1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".priority-high{\r\n");
      out.write("    color:#dc3545;\r\n");
      out.write("    font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".priority-medium{\r\n");
      out.write("    color:#fd7e14;\r\n");
      out.write("    font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".priority-low{\r\n");
      out.write("    color:#198754;\r\n");
      out.write("    font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<h2>All Complaints</h2>\r\n");
      out.write("\r\n");
      out.write("<!-- ==========================\r\n");
      out.write("     SEARCH SECTION\r\n");
      out.write("========================== -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"search-box\">\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath());
      out.write("/SearchComplaintServlet\"\r\n");
      out.write("      method=\"get\">\r\n");
      out.write("\r\n");
      out.write("<input\r\n");
      out.write("    type=\"text\"\r\n");
      out.write("    name=\"title\"\r\n");
      out.write("    placeholder=\"Search by Title\">\r\n");
      out.write("\r\n");
      out.write("<select name=\"category\">\r\n");
      out.write("\r\n");
      out.write("<option value=\"All\">All Categories</option>\r\n");
      out.write("<option value=\"Road\">Road</option>\r\n");
      out.write("<option value=\"Water Supply\">Water Supply</option>\r\n");
      out.write("<option value=\"Electricity\">Electricity</option>\r\n");
      out.write("<option value=\"Drainage\">Drainage</option>\r\n");
      out.write("<option value=\"Street Lights\">Street Lights</option>\r\n");
      out.write("<option value=\"Garbage\">Garbage</option>\r\n");
      out.write("<option value=\"Other\">Other</option>\r\n");
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("<select name=\"status\">\r\n");
      out.write("\r\n");
      out.write("<option value=\"All\">All Status</option>\r\n");
      out.write("<option value=\"Pending\">Pending</option>\r\n");
      out.write("<option value=\"In Progress\">In Progress</option>\r\n");
      out.write("<option value=\"Resolved\">Resolved</option>\r\n");
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("<button type=\"submit\">\r\n");
      out.write("🔍 Search\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/ViewComplaintsServlet\">\r\n");
      out.write("\r\n");
      out.write("<button\r\n");
      out.write("    type=\"button\"\r\n");
      out.write("    class=\"reset-btn\">\r\n");
      out.write("\r\n");
      out.write("Reset\r\n");
      out.write("\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- ==========================\r\n");
      out.write("     COMPLAINT TABLE\r\n");
      out.write("========================== -->\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("<th>ID</th>\r\n");
      out.write("<th>User ID</th>\r\n");
      out.write("<th>Title</th>\r\n");
      out.write("<th>Category</th>\r\n");
      out.write("<th>Description</th>\r\n");
      out.write("<th>District</th>\r\n");
      out.write("<th>Mandal</th>\r\n");
      out.write("<th>Village</th>\r\n");
      out.write("<th>Address</th>\r\n");
      out.write("<th>Image</th>\r\n");
      out.write("<th>Status</th>\r\n");
      out.write("<th>Priority</th>\r\n");
      out.write("<th>Action</th>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");


List<Complaint> list =
    (List<Complaint>)request.getAttribute("complaints");

if(list != null && !list.isEmpty()){

    for(Complaint c : list){


      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.print(c.getId());
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.print(c.getUserId());
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.print(c.getTitle());
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.print(c.getCategory());
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.print(c.getDescription());
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.print(c.getDistrict());
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.print(c.getMandal());
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.print(c.getVillage());
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.print(c.getAddress());
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<!-- IMAGE -->\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("\r\n");


if(c.getImage() != null &&
   !c.getImage().trim().isEmpty()){


      out.write("\r\n");
      out.write("\r\n");
      out.write("<img\r\n");
      out.write("src=\"");
      out.print(request.getContextPath());
      out.write("/uploads/");
      out.print(c.getImage());
      out.write("\"\r\n");
      out.write("class=\"complaint-image\"\r\n");
      out.write("alt=\"Complaint Image\">\r\n");
      out.write("\r\n");


}else{


      out.write("\r\n");
      out.write("\r\n");
      out.write("No Image\r\n");
      out.write("\r\n");


}


      out.write("\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<!-- STATUS -->\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("\r\n");
      out.print(c.getStatus());
      out.write("\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<!-- PRIORITY -->\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("\r\n");


String priority = c.getPriority();

if("High".equalsIgnoreCase(priority)){


      out.write("\r\n");
      out.write("\r\n");
      out.write("<span class=\"priority-high\">\r\n");
      out.write("🔴 High\r\n");
      out.write("</span>\r\n");
      out.write("\r\n");


}else if("Low".equalsIgnoreCase(priority)){


      out.write("\r\n");
      out.write("\r\n");
      out.write("<span class=\"priority-low\">\r\n");
      out.write("🟢 Low\r\n");
      out.write("</span>\r\n");
      out.write("\r\n");


}else{


      out.write("\r\n");
      out.write("\r\n");
      out.write("<span class=\"priority-medium\">\r\n");
      out.write("🟡 Medium\r\n");
      out.write("</span>\r\n");
      out.write("\r\n");


}


      out.write("\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("<!-- ACTION -->\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("\r\n");
      out.write("<a\r\n");
      out.write("    href=\"");
      out.print(request.getContextPath());
      out.write("/ComplaintDetailsServlet?id=");
      out.print(c.getId());
      out.write("\"\r\n");
      out.write("    style=\"\r\n");
      out.write("        display:inline-block;\r\n");
      out.write("        padding:6px 12px;\r\n");
      out.write("        background:#0d6efd;\r\n");
      out.write("        color:white;\r\n");
      out.write("        text-decoration:none;\r\n");
      out.write("        border-radius:5px;\r\n");
      out.write("        margin-bottom:8px;\r\n");
      out.write("    \">\r\n");
      out.write("\r\n");
      out.write("🔍 View Details\r\n");
      out.write("\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("<form\r\n");
      out.write("    action=\"");
      out.print(request.getContextPath());
      out.write("/UpdateStatusServlet\"\r\n");
      out.write("    method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<input\r\n");
      out.write("    type=\"hidden\"\r\n");
      out.write("    name=\"id\"\r\n");
      out.write("    value=\"");
      out.print(c.getId());
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<!-- STATUS -->\r\n");
      out.write("\r\n");
      out.write("<select\r\n");
      out.write("    name=\"status\"\r\n");
      out.write("    class=\"status-select\">\r\n");
      out.write("\r\n");
      out.write("<option\r\n");
      out.write("    value=\"Pending\"\r\n");
      out.write("    ");
      out.print( "Pending".equals(c.getStatus())
        ? "selected" : "" );
      out.write(">\r\n");
      out.write("\r\n");
      out.write("Pending\r\n");
      out.write("\r\n");
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("<option\r\n");
      out.write("    value=\"In Progress\"\r\n");
      out.write("    ");
      out.print( "In Progress".equals(c.getStatus())
        ? "selected" : "" );
      out.write(">\r\n");
      out.write("\r\n");
      out.write("In Progress\r\n");
      out.write("\r\n");
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("<option\r\n");
      out.write("    value=\"Resolved\"\r\n");
      out.write("    ");
      out.print( "Resolved".equals(c.getStatus())
        ? "selected" : "" );
      out.write(">\r\n");
      out.write("\r\n");
      out.write("Resolved\r\n");
      out.write("\r\n");
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<!-- PRIORITY -->\r\n");
      out.write("\r\n");
      out.write("<select\r\n");
      out.write("    name=\"priority\"\r\n");
      out.write("    class=\"priority-select\">\r\n");
      out.write("\r\n");
      out.write("<option\r\n");
      out.write("    value=\"High\"\r\n");
      out.write("    ");
      out.print( "High".equals(c.getPriority())
        ? "selected" : "" );
      out.write(">\r\n");
      out.write("\r\n");
      out.write("🔴 High\r\n");
      out.write("\r\n");
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("<option\r\n");
      out.write("    value=\"Medium\"\r\n");
      out.write("    ");
      out.print( "Medium".equals(c.getPriority())
        ? "selected" : "" );
      out.write(">\r\n");
      out.write("\r\n");
      out.write("🟡 Medium\r\n");
      out.write("\r\n");
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("<option\r\n");
      out.write("    value=\"Low\"\r\n");
      out.write("    ");
      out.print( "Low".equals(c.getPriority())
        ? "selected" : "" );
      out.write(">\r\n");
      out.write("\r\n");
      out.write("🟢 Low\r\n");
      out.write("\r\n");
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<button\r\n");
      out.write("    type=\"submit\"\r\n");
      out.write("    class=\"update-btn\">\r\n");
      out.write("\r\n");
      out.write("Update\r\n");
      out.write("\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");


    }

}else{


      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("<td colspan=\"13\">\r\n");
      out.write("\r\n");
      out.write("No complaints found.\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");


}


      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
